-- 5.Name each show, along with that show’s highest paid actor. (Give the show name, the actor’s name, and the actor’s salary on that show.)--

CREATE OR REPLACE VIEW TVQUERY5 AS
SELECT SH.SHOW_NAME, ACT.ACTOR_NAME, PLAY.ACTOR_SALARY
FROM ZPLAY PLAY, ZTVSHOW SH, ZACTOR ACT
WHERE PLAY.SHOW_NUM = SH.SHOW_NUM
AND ACT.ACTOR_NUM = PLAY.ACTOR_NUM
AND (PLAY.ACTOR_SALARY, PLAY.SHOW_NUM) IN 
    (SELECT MAX(PL.ACTOR_SALARY) AS SALARY , PL.SHOW_NUM
    FROM ZPLAY PL
    GROUP BY (PL.SHOW_NUM)
    )
ORDER BY (SH.SHOW_NAME);
